services:
  - type: web
    name: aditya-portfolio
    runtime: python
    rootDir: portfolio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: RENDER
        value: "true"
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
